---
name: "CI Bicep"

on: # yamllint disable-line rule:truthy
  # push:
  #   branches: [main]
  # pull_request:
  #   branches: [main]

  #=============================================================#
  # The following Variables should be set on the workflow level #
  #============================================================ #
  workflow_dispatch:
    inputs:
      environmentName:
        description: "Name of the Environment"
        required: true
        default: "dev"
      locationName:
        description: "Name of the deployment Location"
        required: true
        default: "westus"
      tenantId:
        description: "Target tenant id (if overriding default)"
        required: false
      subscriptionId:
        description: "Target subscription (if overriding default)"
        required: false

permissions:
  id-token: write
  contents: read
  actions: read
  security-events: write
  issues: read
  checks: write
  pull-requests: write

jobs:
  generate_outputs:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variables with fallback logic
        id: set-values
        run: |
          echo "tenantId=${{ github.event.inputs.tenantId != null && github.event.inputs.tenantId != '' && github.event.inputs.tenantId || secrets.AZURE_TENANT_ID }}"
          echo "subscriptionId=${{ github.event.inputs.subscriptionId != null && github.event.inputs.subscriptionId != '' && github.event.inputs.subscriptionId || secrets.AZURE_SUBSCRIPTION_ID }}"
          echo "tenantId=${{ github.event.inputs.tenantId != null && github.event.inputs.tenantId != '' && github.event.inputs.tenantId || secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV
          echo "subscriptionId=${{ github.event.inputs.subscriptionId != null && github.event.inputs.subscriptionId != '' && github.event.inputs.subscriptionId || secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
    outputs:
      tenantId: ${{ env.tenantId }}
      subscriptionId: ${{ env.subscriptionId }}

  Validate:
    needs: generate_outputs
    uses: ./.github/workflows/template.bicep.validate.yml
    with:
      environmentName: ${{ github.event.inputs.environmentName }}
      environmentDirectory: ${{ github.event.inputs.environmentName }}
      locationName: ${{ github.event.inputs.locationName }}
      branchName: ${{ github.ref_name }}
      githubEnvironment: symphony
      tenantId: ${{ needs.generate_outputs.outputs.tenantId }}
      subscriptionId: ${{ needs.generate_outputs.outputs.subscriptionId }}
    secrets: inherit

  PreviewDeploy:
    needs: [generate_outputs, Validate]
    uses: ./.github/workflows/template.bicep.previewdeploy.yml
    with:
      environmentName: ${{ github.event.inputs.environmentName }}
      environmentDirectory: ${{ github.event.inputs.environmentName }}
      locationName: ${{ github.event.inputs.locationName }}
      branchName: ${{ github.ref_name }}
      githubEnvironment: symphony
      tenantId: ${{ needs.generate_outputs.outputs.tenantId }}
      subscriptionId: ${{ needs.generate_outputs.outputs.subscriptionId }}
    secrets: inherit

  Test:
    needs: [generate_outputs, PreviewDeploy]
    uses: ./.github/workflows/template.bicep.test.yml
    with:
      environmentName: ${{ github.event.inputs.environmentName }}
      locationName: ${{ github.event.inputs.locationName }}
      branchName: ${{ github.ref_name }}
      githubEnvironment: symphony
      tenantId: ${{ needs.generate_outputs.outputs.tenantId }}
      subscriptionId: ${{ needs.generate_outputs.outputs.subscriptionId }}
    secrets: inherit
