---
name: "Destroy Bicep"

on: # yamllint disable-line rule:truthy
  # push:
  #   branches: [main]
  # pull_request:
  #   branches: [main]

  #=============================================================#
  # The following Variables should be set on the workflow level #
  #============================================================ #
  workflow_dispatch:
    inputs:
      environmentName:
        description: "Name of the Environment"
        required: true
        default: "dev"
      locationName:
        description: "Name of the deployment Location"
        required: true
        default: "westus"
      tenantId:
        description: "The target tenant id in which to deploy resources"
        required: true
        default: ${{ secrets.AZURE_TENANT_ID }}
      subscriptionId:
        description: "The target subscription id in which to deploy resources"
        required: true
        default: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

permissions:
  id-token: write
  contents: read

jobs:
  Destroy:
    uses: ./.github/workflows/template.bicep.destroy.yml
    with:
      environmentName: ${{ github.event.inputs.environmentName }}
      locationName: ${{ github.event.inputs.locationName }}
      branchName: ${{ github.ref_name }}
      githubEnvironment: symphony
      tenantId: ${{ github.event.inputs.tenantId }}
      subscriptionId: ${{ github.event.inputs.subscriptionId }}
    secrets: inherit
