---
name: "Cleanup Bicep"

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      pullRequestNumber:
        description: "Pull Request Number"
        required: true
      tenantId:
        description: "The target tenant id in which to deploy resources"
        required: true
        default: ${{ secrets.AZURE_TENANT_ID }}
      subscriptionId:
        description: "The target subscription id in which to deploy resources"
        required: true
        default: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

permissions:
  id-token: write
  contents: read

jobs:
  Destroy:
    uses: ./.github/workflows/template.bicep.cleanup.yml
    with:
      pullRequestnumber: ${{ github.event.inputs.pullRequestNumber }}
      githubEnvironment: symphony
      tenantId: ${{ github.event.inputs.tenantId }}
      subscriptionId: ${{ github.event.inputs.subscriptionId }}
    secrets: inherit
